### ISSUE TITLE
import of thetis followed by import thetis_adjoint gives unwanted results

### ISSUE THREAD

**Issue by stephankramer** [thetisproject/thetis#51]
Not sure this is fixable - but it would be good to discuss.

If thetis is imported before thetis_adjoint the exported firedrake object such as solve, Function, etc. are the standard firedrake ones, and not the firedrake_adjoint wrappers, which obviously breaks the adjoint capability. For instance:

    $ python -c "from thetis_adjoint import *; print solve.__module__"
    dolfin_adjoint.solving
    $ python -c "from thetis import *; from thetis_adjoint import *; print solve.__module__"
    firedrake.solving

The reason is that if thetis is already imported, the from `thetis import *` at the last line of thetis_adjoint/\_\_init\_\_.py just reuses the already loaded thetis module, and thus never executes the `from firedrake_adjoint import *` in thetis/firedrake.py. Just adding an extra `from firedrake_adjoint import *` after the `from thetis_adjoint import *` (or equivalently adding this as the last line of thetis_adjoint/\_\_init\_\_.py) does not help as the symbols used by thetis itself will still be the original firedrake ones.

One of the things that this breaks is the py.test tests. If I run the adjoint tests (which have `from thetis_adjoint import *`) individually, they run fine; if I run them together with the other tests they break, as they will have been preceded by tests that have imported thetis.

**Comment by wence-** [comment]
As you note, the problem is that, having imported thetis, we can't go round again and rewrite all the imported symbols to be the dolfin_adjoint rather than the firedrake ones.

For the purposes of the tests, I think the only sane thing to do is to split the adjoint tests out from the other tests and then test them in a separate pytest instance.

For general use one could imagine all sorts of disgusting hacks with lazy loading and so forth, but I think that's not a good idea.

**Comment by wence-** [comment]
I think this is resolved?

**Comment by stephankramer** [comment]
Yes: not easy to fix in general - tests were fixed by splitting them out and running them seperately.
